US003 - View Capability a role belongs to
Criofann/JobForge-UI pull request #12
Opened 2023-12-06 11:40 UTC by OdhranHague

As a Kainos employee

I want to be able to see what capability each role falls within
So that I can see what capability the role is within Kainos corporate structure

Acceptance Criteria

Update the job roles list page to show the capability name each role belongs to

- Updated getRoles query to include the "CapabilityName" field
- Updated "Role" class constructor to include capability name

2023-12-06 14:17 UTC, jkelso662 commented
Would be good to always have a screenshot for UI PRs :)

2023-12-06 14:20 UTC, jkelso662 requested changes
Think I spotted a bug might need checked out. Also you have a duplicated Role.ts file. Sort these and maybe and a screenshot of your UI and can get this approved :)

2023-12-06 14:20 UTC, jkelso662 commented on views/roles.html
> +                        <td><a href="role.sharepointLink">Sharepoint</a></td>
🐛

2023-12-12 14:07 UTC, OdhranHague commented
- UI for viewing capability
![Screenshot 2023-12-12 at 14 03 23](https://github.com/Criofann/JobForge-UI/assets/145450866/2a7e7950-a811-4a9e-9a42-ceb52d90a506)

I have been running into issues with that duplicated role.ts file. The "Role.ts" is the only one there locally and when i pull down "role.ts", it never appears. I have just manually deleted the file and committed it through Github

2023-12-12 14:12 UTC, Joseph-Magee approved these changes
looks good

2023-12-13 11:20 UTC, lullabelle approved these changes
changes approved

2023-12-13 11:21 UTC, jkelso662 approved these changes

2024-01-10 12:27 UTC, UserConor approved these changes
Looks good, but will need the new UI implemented once it's complete

2024-01-11 15:36 UTC, merged