US002 view job spec
Criofann/JobForge-UI pull request #15
Opened 2023-12-19 09:26 UTC by OdhranHague

As a Kainos Employee

I want to find job specification information about each role
So that I know what is expected for each role

Acceptance Criteria:

- [ ] Able to click on the job role in the table 

- [ ] Can view job spec summary for each role

- [ ] Can view and follow link to Job Spec for each role in SharePoint"

This is what the UI page currently looks like:
![Screenshot 2023-12-18 at 11 07 22](https://github.com/Criofann/JobForge-UI/assets/145450866/3fe7acfb-25f5-4d42-82c8-2998e5ab8674)

After clicking on the name of the role you can view it in full:
![Screenshot 2023-12-19 at 09 25 50](https://github.com/Criofann/JobForge-UI/assets/145450866/438ce5dd-0b70-4bfe-beb6-231781ef5d03)

2023-12-19 09:50 UTC, Joseph-Magee approved these changes
looks good

2023-12-19 14:11 UTC, jkelso662 requested changes
Great! Really good PR just two wee things to fix - make sure you're we are treating this like a real Kainos project repo.

2023-12-19 14:11 UTC, jkelso662 commented on validator/roleValidator.ts
❤️

2023-12-19 14:11 UTC, jkelso662 commented on test/unit/service/roleServiceTests.ts
> +};
This wouldn't get into a real project repo. Needs to be at least sensible info!

2023-12-21 14:24 UTC, jkelso662 approved these changes
👍

2023-12-22 09:52 UTC, merged