Us012 add new job
Criofann/JobForge-UI pull request #17
Opened 2023-12-20 09:44 UTC by Joseph-Magee

As an Admin

I want to add a new role to an existing capability and band
So that I can keep the software information up to date

Acceptance criteria

Able to add a new role to an existing band and capability

Able to define band for new role

Able to define job family for new role

Able to add details to new role:

Job role name

Job spec summary

Sharepoint link

![Screenshot 2023-12-19 at 15 40 14](https://github.com/Criofann/JobForge-UI/assets/145451141/f11e2afc-5063-4879-b323-a7e690157903)

2023-12-20 09:46 UTC, Criofann approved these changes
Looks good, all checks passed and tested well

2023-12-21 12:04 UTC, jkelso662 requested changes
Very good! Just a few things to watch out for i.e. leaving in console.logs. Also would be nice if you could update your PR title to have US instead of Us. Just looks so much more consistent 😄

2023-12-21 12:04 UTC, jkelso662 commented on controller/roleController.ts
> +
Lots of blank space!

2023-12-21 12:04 UTC, jkelso662 commented on service/roleService.ts
> +            console.log(role);
I think you forgot to remove these!

2023-12-21 12:04 UTC, jkelso662 commented on service/roleService.ts
> +                console.log("here");
And this one :P

2023-12-21 12:04 UTC, jkelso662 commented on test/unit/service/familyServiceTest.ts
> +  it("should return Could not create family from 500 error", async () => {
Spacing/tabulation in this file looks a little off.

2023-12-22 14:35 UTC, jkelso662 requested changes
Code looks good! Would approve but I'll save you the time this getting to signoff to realise there are more fixes... From a UX perspective those form labels shouldn't be camelCase. Also the customer says they don't like those form fields being that long. Need to be a bit shorter. Hope this helps :)

2023-12-22 14:36 UTC, jkelso662 commented on validator/roleValidator.ts
> +
Watch out for random unneeded whitespace!

2023-12-22 15:13 UTC, Criofann submitted a review, later dismissed
Looks good to me !

2024-01-10 14:01 UTC, steveh2707 commented on controller/roleController.ts
> +    app.get("/job-role-spec/:roleName", async (req: Request, res: Response) => {
remove individual role from pull request

2024-01-10 15:12 UTC, steveh2707 commented on test/unit/service/roleServiceTests.ts
why is there a roleService test file and a roleServiceTests test file?

2024-01-11 15:36 UTC, merged