US040 login system
Criofann/JobForge-UI pull request #19
Opened 2023-12-22 14:40 UTC by OdhranHague

UI page created for logging in:
--
<img width="1670" alt="Screenshot 2023-12-22 at 14 35 36" src="https://github.com/Criofann/JobForge-UI/assets/145450866/b76de92b-988c-4bae-9d51-90a7a744071f">

<img width="1680" alt="Screenshot 2023-12-22 at 14 35 43" src="https://github.com/Criofann/JobForge-UI/assets/145450866/c8ac82aa-6f51-45c6-a7be-4e03e9446d89">

Error message whenever username / password is incorrect:

<img width="1370" alt="Screenshot 2023-12-22 at 14 36 43" src="https://github.com/Criofann/JobForge-UI/assets/145450866/309fb5f2-c485-4dcb-871b-95d5638f3cff">

Whenever login is valid it renders a main menu boiler plate page

2023-12-22 14:47 UTC, Joseph-Magee commented on test/unit/service/authServiceTests.ts
commented out code

2023-12-22 14:47 UTC, Joseph-Magee commented on views/login.html
remove emplty lines

2023-12-22 14:49 UTC, Joseph-Magee approved these changes
looks good

2023-12-22 15:05 UTC, jkelso662 requested changes
Really close! Just a couple of changes and this is good to go!

2023-12-22 15:05 UTC, jkelso662 commented on controller/roleController.ts
> +            dataa = await bandService.getAllBands();
typo!

2023-12-22 15:05 UTC, jkelso662 commented on controller/roleController.ts
> +        res.render("roles", { roles : data, bands : dataa});
typo!

2023-12-22 15:05 UTC, jkelso662 commented on test/ui/login.js
> +        }
Big function! Consider refactoring at some point but not making it a blocker if you want to carry on

2023-12-22 15:05 UTC, jkelso662 commented on service/familyService.ts
> +            console.log(RoleFamily);
Should this be in there?

2023-12-22 15:17 UTC, jkelso662 commented on public/css/style.css
> +    background: -webkit-linear-gradient(to right, 	#283583, #41679f, #009fe3);
Random white space here!

2023-12-22 15:17 UTC, jkelso662 approved these changes

2024-01-09 15:26 UTC, Joseph-Magee approved these changes
looks good

2024-01-10 11:07 UTC, UserConor reviewed
Great UI! Only small thing is maybe change the copyright to @ 2024 but isn't a requirement

2024-01-11 10:59 UTC, closed without merging